name: Version
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        shell: bash
        run: |
          DESC="
          Commit message:
          ${{ github.event.workflow_run.head_commit.message }}"

          BODY=$(jq -nc \
            --arg title "Website Update" \
            --arg desc "$DESC" \
            --arg url  "https://github.com/WaspScripts/wasp-webapp/commit/${{ github.event.workflow_run.head_commit.id }}" \
            --arg foot "Author: ${{ github.event.workflow_run.head_commit.author.name }}" \
            --argjson color 16742912 \
            '{embeds:[{title:$title,description:$desc,url:$url,color:$color,footer:{text:$foot}}]}')
          curl \
              -H "Content-Type: application/json" \
              -d "$BODY" \
              ${{ secrets.UPDATES_WEBHOOK }}
